apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-node-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: registry.ng.bluemix.net/flask-node/app
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 5000
